### ISSUE TITLE
Configuration prompt does not accept channel values

### ISSUE THREAD

**Issue by kristjantoots** [zpotoloom/nbot#4]
Configuration prompt does not accept channel values. Even if I enter correct value, it just prompts for another channel value indefinitely. 

![2018-05-11 15_23_23-setup js - nbot - visual studio code](https://user-images.githubusercontent.com/2041557/39924137-587dfb74-552f-11e8-8b58-1ffac31c2027.png)

**Comment by zpotoloom** [comment]
Current behavior is to press Ctrl+C to stop adding channels, should prompt about that

**Comment by kristjantoots** [comment]
I think current behavior - even with Ctrl+C - does not match user expectations. Users do not care that behind the scenes this promp type is an array

Maybe we should convert the type to be string, and accept entries which will match patterns like `<#channel> or <#channel, #channel>`?

![2018-05-11 15_54_36-setup js - nbot - visual studio code](https://user-images.githubusercontent.com/2041557/39925291-bbeed580-5533-11e8-8536-027b249c5a44.png)
